import React from 'react';

const Composition = () => {
    return(
    <div >
    <p>Podcasts, commercials, social media posts, artwork, YouTube videos, and literature become testing grounds for rhetorical analysis in my composition courses. I prioritize modern, multimedia objects that represent issues of public importance for analysis because I require similarly relevant, multimodal products from my class. I want students to leave the course able to interrogate primary sources, develop defensible claims based on their analysis, deploy secondary sources proactively, and convey their findings in a format and style suited to a specific audience. </p>
    
    <p>In first-year composition, the class practices topic selection by generating discipline-specific research questions from an episode of the podcast <em>This American Life</em> on social media censorship. Then students investigate unresolved public issues that interest them personally before they present speeches on their preexisting knowledge and persisting questions about research topics. I deploy politically or culturally relevant images or videos to practice conducting rhetorical analysis and answering research questions. Through small-group discussion and impromptu secondary research, students determine the function, impact, and context of Kehinde Wiley’s portrait of Barack Obama, the NRA’s “Violence of Lies” ad, and the response from Los Angeles activists to the NRA. I want students to be critical researchers, capable of determining a source’s reliability and relevance; the class learns to recognize quality secondary sources by evaluating articles from <em>The Atlantic, Huffington Post, </em>and <em>Political Science Quarterly </em>for credibility and bias. An episode of the podcast <em>Code Switch </em>on blackface in the twenty-first century presents a model of source synthesis; students deconstruct a transcript of the podcast, identifying the number and type of sources provided to portray another’s argument or defend their own claims. The class deliberates on the stakeholders of Sharon Olds’s poem “The End,” Ernest Hemingway’s short story “Hills Like White Elephants,” and Roxanne Gay’s article “The Alienable Rights of Women” to develop realistic representations of the audiences they hope to reach. I assign peer review, multiple drafts, and a final presentation to reinforce students’ audience analysis skills in common modes of academic communication. </p>
    
    <p>I have employed these teaching strategies in basic writing and first-year composition courses that practiced process or Writing Across the Curriculum pedagogies. My methods have proven effective in classes of traditional students, non-native speakers of English, and students admitted on probationary basis. For example, in Basic Writing, I introduced the concept of a literacy history, a personal narrative that asked students to construct their identity as readers or writers, with excerpts from Frederick Douglass’s autobiography. Both the literacy history and the final project of the semester—an argumentative letter to a professional—required students to personally invest in their writing. One student wrote to a local judge about the implications of a light sentence in a recent child molestation case; another addressed to the Missouri State University administration compared the time, cost, and confusion first-time college students encounter to features of a poorly made videogame. Incorporating culturally relevant readings and nontraditional primary sources expanded the range of research topics my students pursued and deepened their investment in learning the strategies of academic argumentative writing. </p>
    
    <p>Teaching observations note the intelligent, open-minded culture I encourage in class, the relevant course material I assign, the cohesion between sessions and activities I create, and the wide definition of ‘text’ I instill in my students. On average, students evaluate my overall teaching effectiveness and promptness in returning assignments as far above average, as well as my ability to encourage critical and independent thinking, respond to a wide range of questions, and grade fairly.</p>
    </div>
    
    )}


export default Composition;