import React from 'react';
const Dissertation = () => {
    return (
        <React.Fragment>
        <>
        <h1>Dissertation Abstract</h1>
        <p>The study of punctuation before the age of print is often isolated to a single manuscript, the work of a single scribe, or the manuscript witnesses of a single text. The most wide-sweeping analysis of punctuation to date is M.B. Parkes’s <em>Pause and Effect: Punctuation in the West, </em>which categorizes notational systems according to function and period of use. While narrowly focused studies and broad overviews provide us with discrete examples of punctuation use and a history of overlapping notational systems, neither focus on punctuation as an indicator of how people read. My dissertation “Accent and Embellishment / A History of the Virgule from Grammar Handbook to Liturgical Leaf” demonstrates that punctuation and interpretation are one and the same. The four chapters are a chronological history of punctuation beginning in the first century CE and extending to the fifteenth. I present the history of the virgule or slash (/)as a measure of how students read and interpreted texts first by methods taught in grammar handbooks but then according to scribal-driven innovations to the page. The dissertation contrasts the punctuation we see in extant codices with punctuation from the perspectives of the grammarians who taught it and the academics who applied it. I couple evidence from the papyri or manuscripts with the statements of contemporary figures, such as Cassiodorus or Alcuin. The accounts given in grammars, encyclopedias, reference works, and private correspondence reveal that punctuation trends are a result of changes to the concept of reading and how much interpretive responsibility scribes allowed readers; the responsibilities once considered as acts of interpretation left to the reader became expectations for the appearance of texts placed upon the scribe.</p>

        <p>The introduction answers the question ‘What is a virgule?’ Scholars of Middle and Early Modern English will recognize the slash or virgule (/), from Latin <em>virgula</em>, in medieval manuscripts as a straight pen stroke that is neither part of the formation of a letter nor a mark of abbreviation. In early use it could be horizontal or vertical. Later, it typically appeared as a forward-leaning slash mark (/). In fourteenth-, fifteenth-, and sixteenth-century poetry, the stroke is found within or sometimes at the end of written lines, marking any pause before the final one. Now the slash is most often seen in alternative designators (e.g., Mr./Mrs./Miss/Ms.), mathematics, and computer languages, such as HTML5.</p>

        <p>The first chapter, “Reading Unseparated Text: <em>Distinctiones</em> in First- to Seventh-Century Grammars &amp; Carolingian-Period Codices,” describes the formatting of early Greek and Latin texts, the processes by which readers interpreted texts, and contemporary descriptions of the formal system of punctuation in the Early Middle Ages. <em>Distinctiones </em>refers to the three-point system first observed in manuscripts around the fifth century but recommended in grammatical treatises as early as the late first century CE. Punctuation was intended as a literal measure of the reader’s comprehension because readers inserted these points into unseparated text. Despite its many recommendations, readers rarely adhered to the system of <em>distinctiones </em>at all, often using just two points or none whatsoever. The virgule operates as an outsider to <em>distinctiones, </em>the dominant mode of punctuation until the ninth century CE.</p>

        <p>“Ancient Origins of Interpretation: Tracking the Virgule from the Third Century BCE to the Ninth CE” shows how the term <em>virgula </em>specialized from its original sense “twig” to the “stroke” of accents and critical marks over the course of the first century CE to the ninth. In this chapter, I survey the works of Quintilian, Martianus Capella, Donatus, Diomedes, Isidore of Seville, and Remigius of Auxerre for applications of <em>virgula. </em>The term most frequently describes the acute, longus, and brevis accents, as well as two critical marks, the obolus and lemniscus. One mark to which <em>virgula </em>is applied is the hyphen, the function of which is both performative and syntactical, half accent and half punctuation mark. Readers applied accents, critical signs, and punctuation marks to divide text, indicating that the defining characteristic of punctuation, its relationship to syntax, is a modern development. </p>

        <p>“Innovation and Exemplars: the Virgule’s Role in Insular Book Production During the Eighth and Ninth Centuries” proves that the virgule in eighth- and ninth-century Insular manuscripts was not an imitation of Roman exemplars but a result of increased demand for books. The virgule primarily functioned as a run-over mark in manuscripts produced in Northumbrian scriptoria and written in Irish or Anglo-Saxon Minuscule. Though some of the most famous products of Wearmouth Jarrow were byproducts of the exemplars Benedict Biscop and Ceolfrid brought back from Italy, such as the Codex Amiatinus, an increased demand for copies, especially of Bede’s works, resulted in economical adaptations to script and notation. The application of the virgule appears to coincide with the adoption of Insular Minuscule as a more efficient means of copying books for export to England.</p>

        <p>“Restoring Punctuation to ‘the Hands of the Copyists:’ the Virgule in Notational Systems on the Continent from the Ninth to Eleventh Centuries” demonstrates that punctuation was subsumed under the emendation process to ensure the proper recitation and interpretation of ecclesiastical texts. During the Carolingian Renaissance, Alcuin, an influential figure at the center of Charlemagne’s program of educational reform, specifically requested scribes insert <em>distinctiones </em>as they copied liturgical manuscripts. Though Insular scribes regularly inserted punctuation and word spacing, continental texts were less consistently spaced and sporadically punctuated. Alcuin’s education at York may have encouraged him to redistribute interpretive responsibility from readers to scribes by inserting punctuation during the copying process. The educational reforms of the ninth to eleventh centuries resulted in a multiplication of the number and complexity of notational systems designed for specific applications, including neums and <em>positurae, </em>two systems that feature the slash mark. </p>

        <p>The conclusion, "The Virgule in Personalized Punctuation Systems of the Ars Dictaminists," concerns the <em>ars dictaminis </em>or letter-writing tradition of the twelfth to fifteenth centuries. The <em>ars dictaminists </em>recommended idiosyncratic punctuation systems, and Boncompagno da Signa offered a two-fold system featuring an upright and a horizontal virgule. The Italian humanists applied similarly personalized repertories of punctuation with more symbols fulfilling more precise syntactic roles. Eventually, the virgule would become a common punctuation mark in fourteenth-, fifteenth-, and sixteenth-century Middle English poetry, including in the earliest surviving copies of <em>The Canterbury Tales</em>. The mark can still be seen in early printed editions until it is effectively replaced by the comma in the mid-sixteenth century.</p>

        <p>The history of the virgule is indicative of how readers theorized, categorized, and adopted novel signs to meet their interpretive needs until those needs were met by scribes, editors, and authors. The significance of this argument is twofold: first, punctuation historically functions as a record of readers’ and eventually scribes’ interpretations; second, punctuation trends are influenced by the same forces acting upon scripts, including purpose of use, comprehensibility of writing, treatment of exemplars, and demand for copies. The dissertation recontextualizes the idiosyncratic features of texts as our most valuable insights into the history of manuscript reception and production.</p>
 

        </>
        </React.Fragment>
    )
}

export default Dissertation;